
settings:
  advise_cla_signing: 
    - "Ok"
  popup_for_contributors:
    enabled: tree
    message_text: WebFundamentals is isdhfj transitioning to web.dev, and for now, this project is no longer accepting translations from contributors. Your translations will no longer be reviewed and sent as Pull Requests. Please stay tuned for future updates on the <a href="https://web.dev">web.dev</a> project.
frontmatter_not_escaped: Netrue